apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: katka-node-art2 
  janus-idp.io/tekton: katka-node-art2
  backstage.io/kubernetes-id: katka-node-art2
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: katka-node-art2
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml