apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: katka-node-art2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: katka-node-art2 
  name: katka-node-art2
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: katka-node-art2
    weight: 100 
